@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model <<Rectangle>>{
Class "<<interface>>\nReadOnlyExpenditureExpert" as ReadOnlyExpenditureExpert
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class ExpenditureExpert
Class ModelManager
Class UserPrefs

Class UniqueExpenseList
Class Expense
Class Description
Class ExpenseCategory
Class Amount

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

ExpenditureExpert .up.|> ReadOnlyExpenditureExpert

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyExpenditureExpert
ModelManager -left-> "1" ExpenditureExpert
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

ExpenditureExpert *--> "1" UniqueExpenseList
UniqueExpenseList --> "~* all" Expense
Expense *--> Description
Expense *--> ExpenseCategory
Expense *--> Amount

Expense -[hidden]right-> Description
ExpenseCategory -[hidden]right-> Amount

ModelManager -->"~* filtered" Expense
@enduml
